ASSIGNED = 'ASSIGNED'
IN_PROGRESS = 'IN_PROGRESS'
UNDER_REVIEW = 'UNDER_REVIEW'
DONE = 'DONE'

STATUS_CHOICES = [
    (ASSIGNED, 'ASSIGNED'),
    (IN_PROGRESS, 'IN_PROGRESS'),
    (UNDER_REVIEW, 'UNDER_REVIEW'),
    (DONE, 'DONE'),

]

ROLES = {
    "ADMIN": "ADMIN",
    'LEADER': 'LEADER',
    'MEMBER': 'MEMBER'
}
