# Generated by Django 4.0.6 on 2022-08-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'ADMIN'), ('LEADER', 'LEADER'), ('MEMBER', 'MEMBER')], max_length=1024, null=True),
        ),
    ]
