# Generated by Django 4.0.6 on 2022-08-03 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='team_members_task', to=settings.AUTH_USER_MODEL),
        ),
    ]
